#!/usr/bin/env python3
"""Generate static, crawlable DE/ES/EN product guide pages."""
from pathlib import Path
from html import escape
import json

ROOT = Path(__file__).parent
MARKET = {"de":"amazon.de","es":"amazon.es","en":"amazon.de"}
ATTRIBUTION_DE = {
  "mini":"?maas=maas_adg_AE5B9567A0182F2A31DE4DF7F273EBB2_afap_abs&ref_=aa_maas&tag=maas",
  "large":"?maas=maas_adg_0BEAA17AA1DDCF682F15A9E8149FA401_afap_abs&ref_=aa_maas&tag=maas",
  "swabs":"?maas=maas_adg_F54DD3AFD3762CFFF51D38DE4ECB2724_afap_abs&ref_=aa_maas&tag=maas",
  "clips1":"?maas=maas_adg_70AAAC75B6FB88E9C982FB2C4848DC1E_afap_abs&ref_=aa_maas&tag=maas",
  "clips2":"?maas=maas_adg_6B690D3738FF3BD9DD517B07BAD7CB31_afap_abs&ref_=aa_maas&tag=maas",
  "trolley":"?maas=maas_adg_439851B40722F1B5A72B84D892FB39BC_afap_abs&ref_=aa_maas&tag=maas",
}
ATTRIBUTION_ES = {
  "mini":"?maas=maas_adg_C79490EB0344640BF6976C7A727E3E97_afap_abs&ref_=aa_maas&tag=maas",
  "large":"?maas=maas_adg_DF3C86335F299742022C20CB102F4292_afap_abs&ref_=aa_maas&tag=maas",
  "swabs":"?maas=maas_adg_344285AF5F422F4DD15104F90B2958B9_afap_abs&ref_=aa_maas&tag=maas",
  "clips1":"?maas=maas_adg_B5250B694F0E59126FB1C3BA19B39602_afap_abs&ref_=aa_maas&tag=maas",
  "clips2":"?maas=maas_adg_D4A58E9F22D57C19B77C875FF153E1DF_afap_abs&ref_=aa_maas&tag=maas",
  "trolley":"?maas=maas_adg_45A403A7826DB517DED5B9DEA6BBE6FC_afap_abs&ref_=aa_maas&tag=maas",
}
ATTRIBUTION = {"de": ATTRIBUTION_DE, "es": ATTRIBUTION_ES, "en": ATTRIBUTION_DE}
ROUTES = {
  "mini":{"de":"mini-entwirrbuerste","es":"cepillo-mini-desenredante","en":"mini-detangling-brush"},
  "large":{"de":"entwirrbuerste-l","es":"cepillo-desenredante-l","en":"detangling-brush-l"},
  "swabs":{"de":"bambus-wattestaebchen","es":"bastoncillos-bambu","en":"bamboo-cotton-swabs"},
  "clips1":{"de":"haarklammer-set-1","es":"set-pinzas-pelo-1","en":"claw-clip-set-1"},
  "clips2":{"de":"haarklammer-set-2","es":"set-pinzas-pelo-2","en":"claw-clip-set-2"},
  "trolley":{"de":"friseurwagen","es":"carrito-peluqueria","en":"salon-trolley"},
}
COMMON = {
 "de":{"back":"Alle Produkte","kicker":"Produktguide","buy":"Auf Amazon ansehen","price":"Aktueller Preis, Lieferzeit und Rückgabebedingungen werden auf Amazon angezeigt.","details":"Auf einen Blick","reviews":"Stimmen von Amazon-Kunden","review_note":"Ausgewählte verifizierte Käufe auf Amazon; geprüft am 03.09.2026. Aussagen geben die persönliche Erfahrung der jeweiligen Person wieder.","faq":"Häufige Fragen","trust":"Original von Extendio","trust1h":"EU-weit geschütztes Design","trust1p":"Das Katzenohren-Design der Bürsten ist als EU-Geschmacksmuster Nr. 015112996-0001/-0002 eingetragen.","trust2h":"Eingetragene Marke","trust2p":"Extendio ist eine eingetragene Unionsmarke, EUIPO Nr. 019082088.","trust3h":"Flexibel bestellen","trust3p":"Einzelbestellungen sind über Amazon möglich. Für direkte Anfragen und größere Mengen steht Extendio persönlich zur Verfügung.","finalh":"Passt dieses Produkt zu Ihnen?","finalp":"Details und aktuelle Verfügbarkeit direkt auf Amazon prüfen.","home":"Startseite","legal":"Impressum","privacy":"Datenschutz","cookies":"Cookies","settings":"Cookie-Einstellungen","verified":"Verifizierter Kauf · Amazon.de"},
 "es":{"back":"Todos los productos","kicker":"Guía de producto","buy":"Ver en Amazon","price":"El precio, la entrega y las condiciones de devolución vigentes se muestran en Amazon.","details":"De un vistazo","reviews":"Opiniones de clientes de Amazon","review_note":"Compras verificadas seleccionadas en Amazon; comprobadas el 03.09.2026. Cada comentario refleja la experiencia personal de su autor.","faq":"Preguntas frecuentes","trust":"Original de Extendio","trust1h":"Diseño protegido en la UE","trust1p":"El diseño de orejas de gato de los cepillos está registrado en la UE con los números 015112996-0001/-0002.","trust2h":"Marca registrada","trust2p":"Extendio es una marca de la Unión Europea registrada, EUIPO n.º 019082088.","trust3h":"Pedido flexible","trust3p":"Los pedidos individuales están disponibles en Amazon. Extendio atiende personalmente las consultas directas y los volúmenes mayores.","finalh":"¿Es este producto para ti?","finalp":"Consulta los detalles y la disponibilidad actual directamente en Amazon.","home":"Inicio","legal":"Aviso Legal","privacy":"Privacidad","cookies":"Cookies","settings":"Configuración de cookies","verified":"Compra verificada · Amazon.es"},
 "en":{"back":"All products","kicker":"Product guide","buy":"View on Amazon","price":"The current price, delivery and return terms are shown on Amazon.","details":"At a glance","reviews":"What Amazon customers say","review_note":"Selected verified purchases on Amazon; checked 3 September 2026. Each comment reflects the individual customer's experience.","faq":"Frequently asked questions","trust":"The Extendio original","trust1h":"EU registered design","trust1p":"The brushes’ cat-ear design is registered in the EU under Nos. 015112996-0001/-0002.","trust2h":"Registered trade mark","trust2p":"Extendio is a registered European Union trade mark, EUIPO No. 019082088.","trust3h":"Flexible ordering","trust3p":"Individual orders are available through Amazon. Extendio handles direct enquiries and larger quantities personally.","finalh":"Is this product right for you?","finalp":"Check details and current availability directly on Amazon.","home":"Home","legal":"Legal Notice","privacy":"Privacy Policy","cookies":"Cookies","settings":"Cookie settings","verified":"Verified purchase · Amazon.de"},
}

DATA = {
 "mini":{
  "asin":"B0GD2MV24F","sku":"HB-M-BLK","image":"/assets/mini_lila.jpg",
  "de":{"title":"Extendio Entwirrbürste Mini","meta":"Kompakte Extendio Entwirrbürste Mini für nasses und trockenes Haar, Kinder, Reise und Extensions. Vier Farben; 29 % biobasierter Anteil.","lead":"Kompaktes Katzenohren-Design für Handtasche, Reise und die tägliche Haarpflege — mit flexiblen Nylonborsten für nasses und trockenes Haar.","pills":["17,2 × 7 × 3,7 cm","50 g","Vier Farben","Nass & trocken"],"features":[("Kompaktes Format","Passt in Handtasche oder Reisegepäck und ist auch für Kinderhände gut greifbar."),("Flexible Borsten","Nylonborsten für feines, lockiges, nasses oder trockenes Haar sowie Extensions."),("Geprüfte Materialangabe","Korpus aus Polypropylen und Weizenstrohfaser mit 29 % biobasiertem Kohlenstoff, gemessen nach ASTM D6866.")],"reviews":[("Ziept absolut nicht, sehr zu empfehlen.","Claudia"),("Perfekt für Reisen oder für Kinder.","Amazon Kunde"),("Macht was sie soll und sieht klasse aus.","Christian K.")],"faq":[("Kann die Mini-Bürste auf nassem Haar verwendet werden?","Ja. Sie ist laut Produktangaben für nasses und trockenes Haar vorgesehen."),("Welche Größe hat die Bürste?","Die Mini misst 17,2 × 7 × 3,7 cm und wiegt etwa 50 g."),("Welche Farben gibt es?","Schwarz, Blau, Beige und Lila. Die aktuelle Auswahl sehen Sie auf Amazon."),("Aus welchem Material besteht sie?","Die Borsten bestehen aus Nylon; der Korpus aus Polypropylen und Weizenstrohfaser. Der biobasierte Kohlenstoffanteil des Bürstenkorpus beträgt 29 %.")]},
  "es":{"title":"Cepillo Mini Desenredante Extendio","meta":"Cepillo Mini Extendio para cabello húmedo o seco, niños, viaje y extensiones. Cuatro colores y 29 % de contenido de origen biológico.","lead":"Diseño compacto con orejas de gato para el bolso, los viajes y el cuidado diario, con púas flexibles de nailon para cabello húmedo o seco.","pills":["17,2 × 7 × 3,7 cm","50 g","Cuatro colores","Húmedo y seco"],"features":[("Formato compacto","Cabe en el bolso o equipaje y resulta cómodo también para manos pequeñas."),("Púas flexibles","Púas de nailon para cabello fino, rizado, húmedo o seco y extensiones."),("Dato de material verificado","Cuerpo de polipropileno y fibra de paja de trigo con 29 % de carbono de origen biológico, medido según ASTM D6866.")],"reviews":[("Pequeño para viaje, desenreda bien.","Celia")],"faq":[("¿Se puede usar sobre cabello húmedo?","Sí. Según la información del producto, sirve para cabello húmedo y seco."),("¿Qué tamaño tiene?","Mide 17,2 × 7 × 3,7 cm y pesa aproximadamente 50 g."),("¿Qué colores hay?","Negro, azul, beige y lila. La selección vigente aparece en Amazon."),("¿De qué material está hecho?","Las púas son de nailon; el cuerpo, de polipropileno y fibra de paja de trigo. El cuerpo contiene un 29 % de carbono de origen biológico.")]},
  "en":{"title":"Extendio Mini Detangling Brush","meta":"Compact Extendio Mini Detangling Brush for wet or dry hair, children, travel and extensions. Four colours and 29% bio-based content.","lead":"A compact cat-ear design for handbags, travel and daily care, with flexible nylon bristles for wet or dry hair.","pills":["17.2 × 7 × 3.7 cm","50 g","Four colours","Wet & dry"],"features":[("Compact format","Fits a handbag or travel case and is comfortable for smaller hands."),("Flexible bristles","Nylon bristles for fine, curly, wet or dry hair and extensions."),("Verified material fact","Polypropylene and wheat-straw-fibre body with 29% bio-based carbon, measured to ASTM D6866.")],"reviews":[("Doesn’t pull at all — highly recommended.","Claudia · translated from German"),("Perfect for travelling or for children.","Amazon customer · translated from German"),("Does what it should and looks great.","Christian K. · translated from German")],"faq":[("Can it be used on wet hair?","Yes. The product information specifies use on wet and dry hair."),("How large is it?","The Mini measures 17.2 × 7 × 3.7 cm and weighs approximately 50 g."),("Which colours are available?","Black, blue, beige and purple. See Amazon for the current selection."),("What is it made from?","The bristles are nylon; the body is polypropylene and wheat-straw fibre. The brush body contains 29% bio-based carbon.")]},
 },
 "large":{
  "asin":"B0GD2MXXDT","sku":"HB-L-Large","video":"/assets/brush-l-real-use.m4v?v=2","poster":"/assets/brush-l-real-use-poster.jpg?v=2",
  "de":{"title":"Extendio Entwirrbürste L","meta":"Große Extendio Entwirrbürste L für langes, dickes oder lockiges Haar und Extensions. Flexible Nylonborsten; für nasses und trockenes Haar.","lead":"Mehr Bürstenfläche pro Zug — entwickelt für langes, dickes oder lockiges Haar und für Extensions. Das echte Anwendungsvideo zeigt die Bürste im Einsatz.","pills":["22 × 8 × 3,5 cm","50 g","Große Bürstenfläche","Nass & trocken"],"features":[("Für viel Haar","Die größere Fläche eignet sich für langes, dickes oder lockiges Haar und längere Extensions."),("Flexibles Spiraldesign","Die offene, flexible Form folgt der Bewegung beim Bürsten; Nylonborsten arbeiten durch nasses oder trockenes Haar."),("Geprüfte Materialangabe","Korpus aus Polypropylen und Weizenstrohfaser mit 29 % biobasiertem Kohlenstoff, gemessen nach ASTM D6866.")],"reviews":[("Sie löst schneller die Knoten als leichtere Modelle.","Marie Pascale Wagner")],"faq":[("Für welches Haar ist Größe L gedacht?","Für langes, dickes oder lockiges Haar sowie Extensions, wenn eine größere Bürstenfläche gewünscht ist."),("Kann sie im nassen Haar verwendet werden?","Ja. Sie ist für nasses und trockenes Haar vorgesehen."),("Welche Maße hat sie?","Die Bürste misst 22 × 8 × 3,5 cm und wiegt etwa 50 g."),("Ist das Video echtes Extendio-Material?","Ja. Das Anwendungsvideo wurde mit einer Extendio Bürste produziert.")]},
  "es":{"title":"Cepillo Desenredante L Extendio","meta":"Cepillo desenredante grande Extendio L para cabello largo, grueso o rizado y extensiones. Púas flexibles; uso húmedo o seco.","lead":"Más superficie en cada pasada, pensado para cabello largo, grueso o rizado y para extensiones. El vídeo propio muestra el cepillo durante un uso real.","pills":["22 × 8 × 3,5 cm","50 g","Superficie amplia","Húmedo y seco"],"features":[("Para más cantidad de cabello","La superficie amplia resulta adecuada para cabello largo, grueso o rizado y extensiones largas."),("Diseño espiral flexible","La forma abierta acompaña el movimiento al cepillar; las púas de nailon trabajan sobre cabello húmedo o seco."),("Dato de material verificado","Cuerpo de polipropileno y fibra de paja de trigo con 29 % de carbono de origen biológico, medido según ASTM D6866.")],"reviews":[("Deshace los nudos más rápido que modelos más ligeros.","Marie Pascale Wagner · traducido del alemán")],"faq":[("¿Para qué cabello está pensado el tamaño L?","Para cabello largo, grueso o rizado y extensiones cuando se prefiere una superficie de cepillado más amplia."),("¿Puede usarse con el cabello húmedo?","Sí. Está previsto para cabello húmedo y seco."),("¿Qué medidas tiene?","Mide 22 × 8 × 3,5 cm y pesa aproximadamente 50 g."),("¿El vídeo es material real de Extendio?","Sí. El vídeo de uso fue producido con un cepillo Extendio.")]},
  "en":{"title":"Extendio Detangling Brush L","meta":"Large Extendio Detangling Brush L for long, thick or curly hair and extensions. Flexible nylon bristles for wet or dry hair.","lead":"More brushing surface per stroke, designed for long, thick or curly hair and extensions. Our own video shows the brush in real use.","pills":["22 × 8 × 3.5 cm","50 g","Large brush area","Wet & dry"],"features":[("For more hair","The larger surface suits long, thick or curly hair and longer extensions."),("Flexible spiral design","The open shape moves while brushing; nylon bristles work through wet or dry hair."),("Verified material fact","Polypropylene and wheat-straw-fibre body with 29% bio-based carbon, measured to ASTM D6866.")],"reviews":[("It releases knots faster than lighter models.","Marie Pascale Wagner · translated from German")],"faq":[("Which hair is size L designed for?","Long, thick or curly hair and extensions when a larger brushing surface is preferred."),("Can it be used on wet hair?","Yes. It is intended for wet and dry hair."),("What are its dimensions?","It measures 22 × 8 × 3.5 cm and weighs approximately 50 g."),("Is the video genuine Extendio material?","Yes. The demonstration was produced using an Extendio brush.")]},
 },
 "swabs":{
  "asin":"B0FZM98G9B","sku":"EWS1200","image":"/assets/wattestaebchen.jpg",
  "de":{"title":"Extendio Bambus-Wattestäbchen · 1200 Stück","meta":"Extendio Vorratspack mit 1200 Wattestäbchen: 6 Boxen à 200, Bambusstiel und Baumwollspitzen, hygienisch einzeln entnehmbar.","lead":"Ein großer Vorrat für Bad, Kosmetik und präzise Reinigungsarbeiten: sechs kompakte Boxen mit je 200 Stäbchen.","pills":["1200 Stück","6 × 200","Bambusstiel","Baumwollspitzen"],"features":[("Stabil und weich","Der Bambusstiel bietet Kontrolle; die Baumwollspitzen sind weich und sitzen fest."),("Hygienische Entnahme","Die Verpackungsöffnung ist so gestaltet, dass die Stäbchen am Stiel einzeln entnommen werden können."),("Vielseitig einsetzbar","Für äußere Körperpflege, Make-up und präzise Reinigungsarbeiten. Nicht in den Gehörgang einführen.")],"reviews":[("Wird immer wieder gekauft","Yvi"),("Sind wirklich gut, kein Abknicken beim Reinigen.","G+ S"),("Sehr gutes Produkt, ist jeden Tag im Einsatz.","Dirk Haendschke")],"faq":[("Wie viele Stäbchen sind enthalten?","1200 Stück, aufgeteilt auf sechs Boxen mit je 200 Stück."),("Woraus bestehen sie?","Aus einem Bambusstiel mit Baumwollspitzen."),("Wie werden sie angewendet?","Nur äußerlich verwenden und nicht in den Gehörgang oder andere Körperöffnungen einführen."),("Ist der Artikel immer verfügbar?","Die aktuelle Verfügbarkeit wird direkt auf Amazon angezeigt.")],"facth":"Material klar benannt","factp":"Die Bestandteile sind Bambus und Baumwolle. Wir übernehmen keine darüber hinausgehenden Umweltversprechen."},
  "es":{"title":"Bastoncillos de bambú Extendio · 1200 uds.","meta":"Pack Extendio de 1200 bastoncillos: 6 cajas de 200, varilla de bambú, puntas de algodón y extracción individual.","lead":"Una reserva amplia para baño, maquillaje y tareas de limpieza de precisión: seis cajas compactas de 200 unidades.","pills":["1200 unidades","6 × 200","Varilla de bambú","Puntas de algodón"],"features":[("Firmes y suaves","La varilla de bambú aporta control; las puntas de algodón son suaves y quedan bien fijadas."),("Extracción higiénica","La abertura permite sacar cada bastoncillo por la varilla sin tocar el resto."),("Uso versátil","Para cuidado corporal externo, maquillaje y limpieza precisa. No introducir en el conducto auditivo.")],"reviews":[("Los compramos una y otra vez.","Yvi · traducido del alemán"),("Son buenos y no se doblan al limpiar.","G+ S · traducido del alemán"),("Muy buen producto; lo usamos a diario.","Dirk Haendschke · traducido del alemán")],"faq":[("¿Cuántos incluye?","1200 unidades, repartidas en seis cajas de 200."),("¿De qué están hechos?","De una varilla de bambú con puntas de algodón."),("¿Cómo se utilizan?","Solo para uso externo; no introducir en el conducto auditivo ni en otras cavidades corporales."),("¿Está siempre disponible?","La disponibilidad actual aparece directamente en Amazon.")],"facth":"Materiales claramente indicados","factp":"Los componentes son bambú y algodón. No hacemos promesas medioambientales adicionales."},
  "en":{"title":"Extendio Bamboo Cotton Swabs · 1200 pcs","meta":"Extendio value pack of 1,200 swabs: six boxes of 200, bamboo stems, cotton tips and hygienic single removal.","lead":"A generous supply for bathroom, make-up and precision cleaning: six compact boxes containing 200 swabs each.","pills":["1,200 pieces","6 × 200","Bamboo stem","Cotton tips"],"features":[("Firm and soft","The bamboo stem provides control; the cotton tips are soft and securely attached."),("Hygienic removal","The opening lets you remove one swab by its stem without touching the remaining swabs."),("Versatile use","For external personal care, make-up and precision cleaning. Do not insert into the ear canal.")],"reviews":[("We buy them again and again.","Yvi · translated from German"),("They are really good and do not bend while cleaning.","G+ S · translated from German"),("A very good product; used every day.","Dirk Haendschke · translated from German")],"faq":[("How many are included?","1,200 swabs in six boxes of 200."),("What are they made from?","A bamboo stem with cotton tips."),("How should they be used?","For external use only; do not insert into the ear canal or other body cavities."),("Is the item always available?","Current availability is shown directly on Amazon.")],"facth":"Materials clearly stated","factp":"The components are bamboo and cotton. We make no additional environmental promises."},
 },
 "clips1":{
  "asin":"B0GM6Y1D2G","sku":"HC-4-set","image":"/assets/haarklammern_set1.jpg",
  "de":{"title":"Extendio Haarklammer-Set 1 · Koralle & Lila","meta":"Vier Extendio Claw Clips in zwei Größen und warmen Farbtönen. Matte Oberfläche und kräftige Feder für feines, dickes oder lockiges Haar.","lead":"Vier vielseitige Claw Clips in zwei Größen — für komplette Hochsteckfrisuren, einzelne Partien und schnelle Looks im Alltag.","pills":["4 Klammern","2 Größen","Matte Oberfläche","Starke Feder"],"features":[("Zwei Größen","Große Klammern für mehr Haar und kleinere Clips zum Fixieren einzelner Partien."),("Sicherer Halt","Breite Zähne, eine kräftige Feder und die matte Oberfläche unterstützen einen rutschfesten Sitz."),("Warme Farbwelt","Koralle, Lila, Lavendel und Beige lassen sich vielseitig kombinieren.")],"reviews":[],"faq":[("Für welche Haartypen sind die Klammern gedacht?","Für feines, dickes oder lockiges Haar; die zwei Größen decken unterschiedliche Haarmengen ab."),("Wie viele Klammern enthält das Set?","Vier Klammern in zwei Größen."),("Aus welchem Material bestehen sie?","Aus Polypropylen mit Pflanzen- beziehungsweise Weizenstrohfaser."),("Kann ich zwischen Set 1 und Set 2 wählen?","Ja. Amazon zeigt beide Farbsets als Varianten an.")],"facth":"Dieses Set eindeutig zugeordnet","factp":"Set 1 ist bei Amazon als ASIN B0GM6Y1D2G geführt; Set 2 ist dort als auswählbare Variante verknüpft."},
  "es":{"title":"Set de pinzas Extendio 1 · Coral y lila","meta":"Cuatro pinzas Extendio en dos tamaños y tonos cálidos. Acabado mate y muelle firme para cabello fino, grueso o rizado.","lead":"Cuatro pinzas versátiles en dos tamaños para recogidos completos, secciones y peinados rápidos de diario.","pills":["4 pinzas","2 tamaños","Acabado mate","Muelle firme"],"features":[("Dos tamaños","Pinzas grandes para más cabello y clips pequeños para fijar secciones."),("Sujeción segura","Los dientes anchos, el muelle firme y el acabado mate favorecen un agarre estable."),("Tonos cálidos","Coral, lila, lavanda y beige para combinar con distintos estilos.")],"reviews":[],"faq":[("¿Para qué tipos de cabello?","Para cabello fino, grueso o rizado; los dos tamaños cubren distintas cantidades de cabello."),("¿Cuántas pinzas incluye?","Cuatro pinzas en dos tamaños."),("¿De qué material están hechas?","De polipropileno con fibra vegetal o de paja de trigo."),("¿Puedo elegir entre Set 1 y Set 2?","Sí. Amazon muestra ambos colores como variantes.")],"facth":"Variante identificada","factp":"Amazon identifica el Set 1 con el ASIN B0GM6Y1D2G y lo vincula con el Set 2 como variante."},
  "en":{"title":"Extendio Claw Clip Set 1 · Coral & Purple","meta":"Four Extendio claw clips in two sizes and warm shades. Matte finish and firm spring for fine, thick or curly hair.","lead":"Four versatile claw clips in two sizes for full updos, smaller sections and quick everyday styles.","pills":["4 clips","2 sizes","Matte finish","Firm spring"],"features":[("Two sizes","Large clips for more hair and smaller clips for securing sections."),("Secure hold","Wide teeth, a firm spring and the matte surface support a stable, non-slip fit."),("Warm palette","Coral, purple, lavender and beige work with a range of looks.")],"reviews":[],"faq":[("Which hair types are they for?","Fine, thick or curly hair; the two sizes suit different amounts of hair."),("How many clips are included?","Four clips in two sizes."),("What are they made from?","Polypropylene with plant or wheat-straw fibre."),("Can I choose Set 1 or Set 2?","Yes. Amazon displays both colour sets as variants.")],"facth":"Variant clearly identified","factp":"Amazon lists Set 1 under ASIN B0GM6Y1D2G and links Set 2 as a selectable variant."},
 },
 "clips2":{
  "asin":"B0GQ46QVKM","sku":"HC-4-set-2","image":"/assets/haarklammern_set2.jpg",
  "de":{"title":"Extendio Haarklammer-Set 2 · Mint & Beige","meta":"Vier Extendio Claw Clips in zwei Größen und kühlen Pastelltönen. Matte Oberfläche und kräftige Feder für feines, dickes oder lockiges Haar.","lead":"Das gleiche praktische Format in einer kühleren Farbwelt — vier Claw Clips für Hochsteckfrisuren, einzelne Partien und schnelle Looks.","pills":["4 Klammern","2 Größen","Matte Oberfläche","Starke Feder"],"features":[("Zwei Größen","Große Klammern bündeln mehr Haar; kleine Clips fixieren einzelne Partien."),("Sicherer Halt","Breite Zähne, kräftige Feder und matte Oberfläche unterstützen einen stabilen Sitz."),("Kühle Pastelltöne","Mint, Lavendel und Beige für eine zurückhaltende, moderne Farbwahl.")],"reviews":[],"faq":[("Für welche Haartypen sind die Klammern gedacht?","Für feines, dickes oder lockiges Haar; die zwei Größen decken unterschiedliche Haarmengen ab."),("Wie viele Klammern enthält das Set?","Vier Klammern in zwei Größen."),("Aus welchem Material bestehen sie?","Aus Polypropylen mit Pflanzen- beziehungsweise Weizenstrohfaser."),("Kann ich zwischen Set 1 und Set 2 wählen?","Ja. Amazon zeigt beide Farbsets als Varianten an.")],"facth":"Dieses Set eindeutig zugeordnet","factp":"Set 2 ist bei Amazon als ASIN B0GQ46QVKM geführt; Set 1 ist dort als auswählbare Variante verknüpft."},
  "es":{"title":"Set de pinzas Extendio 2 · Menta y beige","meta":"Cuatro pinzas Extendio en dos tamaños y tonos pastel fríos. Acabado mate y muelle firme para cabello fino, grueso o rizado.","lead":"El mismo formato práctico en tonos más fríos: cuatro pinzas para recogidos, secciones y peinados rápidos.","pills":["4 pinzas","2 tamaños","Acabado mate","Muelle firme"],"features":[("Dos tamaños","Las grandes recogen más cabello y las pequeñas fijan secciones."),("Sujeción segura","Los dientes anchos, el muelle firme y el acabado mate favorecen un agarre estable."),("Pasteles fríos","Menta, lavanda y beige para una combinación discreta y moderna.")],"reviews":[],"faq":[("¿Para qué tipos de cabello?","Para cabello fino, grueso o rizado; los dos tamaños cubren distintas cantidades de cabello."),("¿Cuántas pinzas incluye?","Cuatro pinzas en dos tamaños."),("¿De qué material están hechas?","De polipropileno con fibra vegetal o de paja de trigo."),("¿Puedo elegir entre Set 1 y Set 2?","Sí. Amazon muestra ambos colores como variantes.")],"facth":"Variante identificada","factp":"Amazon identifica el Set 2 con el ASIN B0GQ46QVKM y lo vincula con el Set 1 como variante."},
  "en":{"title":"Extendio Claw Clip Set 2 · Mint & Beige","meta":"Four Extendio claw clips in two sizes and cool pastel shades. Matte finish and firm spring for fine, thick or curly hair.","lead":"The same practical format in a cooler palette: four claw clips for updos, sections and quick everyday styles.","pills":["4 clips","2 sizes","Matte finish","Firm spring"],"features":[("Two sizes","Large clips gather more hair, while smaller clips secure sections."),("Secure hold","Wide teeth, a firm spring and matte finish support a stable fit."),("Cool pastels","Mint, lavender and beige create a restrained, modern palette.")],"reviews":[],"faq":[("Which hair types are they for?","Fine, thick or curly hair; the two sizes suit different amounts of hair."),("How many clips are included?","Four clips in two sizes."),("What are they made from?","Polypropylene with plant or wheat-straw fibre."),("Can I choose Set 1 or Set 2?","Yes. Amazon displays both colour sets as variants.")],"facth":"Variant clearly identified","factp":"Amazon lists Set 2 under ASIN B0GQ46QVKM and links Set 1 as a selectable variant."},
 },
 "trolley":{
  "asin":"B0DKJW844F","sku":"EXT0195","video":"/assets/salon-trolley-cinematic.mp4","poster":"/assets/salon-trolley-cinematic-poster.jpg",
  "de":{"title":"Extendio Salon Trolley","meta":"Höhenverstellbarer Extendio Friseurwagen mit Ablage, zwei herausnehmbaren Schalen, Werkzeugöffnungen und Rollen für den Salonalltag.","lead":"Arbeitsmaterial genau dort, wo es gebraucht wird: ein höhenverstellbarer Wagen für Extensions, Farbe und Styling direkt am Stuhl.","pills":["Höhenverstellbar","2 herausnehmbare Schalen","Werkzeugöffnungen","Rollen"],"features":[("Arbeitsfläche am Stuhl","Ablagefläche für Werkzeuge und Material während Extensions-, Farb- oder Stylingarbeiten."),("Flexibel organisiert","Zwei herausnehmbare Schalen und integrierte Öffnungen halten häufig genutzte Werkzeuge griffbereit."),("Für den Salonalltag","Die Rollen erleichtern den Wechsel zwischen Arbeitsplätzen; die Höhe lässt sich an die jeweilige Situation anpassen.")],"reviews":[],"faq":[("Wofür eignet sich der Wagen?","Für Extensions-, Farb- und Stylingarbeiten sowie als mobile Ablage im Salon."),("Sind Schalen enthalten?","Ja. Zum Lieferumfang gehören zwei herausnehmbare Schalen."),("Ist der Wagen höhenverstellbar?","Ja. Die Arbeitshöhe kann angepasst werden."),("Gibt es Konditionen für mehrere Wagen?","Für größere Mengen erstellen wir ein separates Angebot. Nutzen Sie den Großhandelskontakt auf der Startseite.")],"facth":"Für professionelle Abläufe","factp":"Ausstattung und Einsatzbereiche sind konkret beschrieben; für mehrere Wagen bieten wir auf Anfrage gesonderte Konditionen."},
  "es":{"title":"Carrito de Peluquería Extendio","meta":"Carrito de peluquería Extendio regulable en altura, con bandeja, dos recipientes extraíbles, soportes para herramientas y ruedas.","lead":"Material de trabajo justo donde se necesita: carrito regulable en altura para extensiones, color y peinado junto al sillón.","pills":["Altura regulable","2 recipientes extraíbles","Soportes para herramientas","Ruedas"],"features":[("Superficie junto al sillón","Bandeja para herramientas y material durante trabajos de extensiones, color o peinado."),("Organización flexible","Dos recipientes extraíbles y aberturas integradas mantienen a mano las herramientas frecuentes."),("Para el trabajo diario","Las ruedas facilitan el cambio entre puestos y la altura se adapta a cada tarea.")],"reviews":[],"faq":[("¿Para qué trabajos sirve?","Para extensiones, color, peinado y como superficie móvil en el salón."),("¿Incluye recipientes?","Sí. Incluye dos recipientes extraíbles."),("¿Es regulable en altura?","Sí. La altura de trabajo puede ajustarse."),("¿Hay condiciones para varias unidades?","Para cantidades mayores preparamos una oferta aparte. Utiliza el contacto mayorista de la página principal.")],"facth":"Pensado para el trabajo profesional","factp":"El equipamiento y los usos están descritos de forma concreta; ofrecemos condiciones aparte para varias unidades."},
  "en":{"title":"Extendio Salon Trolley","meta":"Height-adjustable Extendio salon trolley with worktop, two removable bowls, tool openings and castors for professional salon routines.","lead":"Keep working materials where they are needed: a height-adjustable trolley for extensions, colour and styling beside the chair.","pills":["Height adjustable","2 removable bowls","Tool openings","Castors"],"features":[("Worktop by the chair","Space for tools and materials during extension, colour or styling services."),("Flexible organisation","Two removable bowls and integrated openings keep frequently used tools within reach."),("For daily salon work","Castors help move between stations, while the working height adjusts to the task.")],"reviews":[],"faq":[("What is the trolley designed for?","Extension, colour and styling work, and as a mobile salon work surface."),("Are bowls included?","Yes. Two removable bowls are included."),("Is it height adjustable?","Yes. The working height can be adjusted."),("Are volume terms available?","For larger quantities, we prepare a separate quotation. Use the wholesale contact on the home page.")],"facth":"Built for professional routines","factp":"Equipment and use cases are described in concrete terms; separate volume terms are available on request."},
 }
}

def page(product, lang):
    c, d = COMMON[lang], DATA[product][lang]
    route = ROUTES[product][lang]
    url = f"https://extendio.es/{lang}/{route}/"
    amazon_base = f"https://www.{MARKET[lang]}/dp/{DATA[product]['asin']}"
    amazon = amazon_base + ATTRIBUTION.get(lang, {}).get(product, "")
    alts = "\n".join(f'<link rel="alternate" hreflang="{l}" href="https://extendio.es/{l}/{ROUTES[product][l]}/">' for l in ("de","es","en"))
    alts += f'\n<link rel="alternate" hreflang="x-default" href="https://extendio.es/en/{ROUTES[product]["en"]}/">'
    langlinks = "".join(f'<a href="/{l}/{ROUTES[product][l]}/" {("aria-current=" + chr(34) + "page" + chr(34)) if l==lang else ""}>{l.upper()}</a>' for l in ("de","es","en"))
    media = (f'<video autoplay muted loop playsinline preload="metadata" poster="{DATA[product]["poster"]}" aria-label="{escape(d["title"])}"><source src="{DATA[product]["video"]}" type="video/mp4"></video>' if "video" in DATA[product] else f'<img src="{DATA[product]["image"]}" alt="{escape(d["title"])}">')
    pills = "".join(f'<span class="pill">{escape(x)}</span>' for x in d["pills"])
    features = "".join(f'<article class="box"><h3>{escape(h)}</h3><p>{escape(p)}</p></article>' for h,p in d["features"])
    reviews = ""
    if d["reviews"]:
      cards = "".join(f'<article class="box"><div class="stars" aria-label="5 von 5">★★★★★</div><p>{escape(q)}</p><div class="review-meta">{escape(a)}<br>{escape(c["verified"])}</div></article>' for q,a in d["reviews"])
      reviews = f'<section class="section white reviews"><div class="wrap"><h2>{c["reviews"]}</h2><p class="section-intro">{c["review_note"]}</p><div class="grid">{cards}</div></div></section>'
    faqs = "".join(f'<details><summary>{escape(q)}</summary><p>{escape(a)}</p></details>' for q,a in d["faq"])
    faq_schema = [{"@type":"Question","name":q,"acceptedAnswer":{"@type":"Answer","text":a}} for q,a in d["faq"]]
    fact_h = d.get("facth", c["trust1h"])
    fact_p = d.get("factp", c["trust1p"])
    schema = {"@context":"https://schema.org","@graph":[{"@type":"WebPage","name":d["title"],"description":d["meta"],"image":"https://extendio.es"+(DATA[product].get("poster") or DATA[product]["image"]),"url":url,"isPartOf":{"@type":"WebSite","name":"Extendio","url":"https://extendio.es/"},"about":{"@type":"Thing","name":d["title"],"sameAs":amazon_base}},{"@type":"FAQPage","mainEntity":faq_schema}]}
    return f"""<!doctype html><html lang="{lang}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{escape(d["title"])} | Extendio</title><meta name="description" content="{escape(d["meta"])}"><meta name="robots" content="index,follow,max-image-preview:large"><link rel="canonical" href="{url}">{alts}<meta property="og:type" content="product"><meta property="og:title" content="{escape(d["title"])}"><meta property="og:description" content="{escape(d["meta"])}"><meta property="og:url" content="{url}"><meta property="og:image" content="https://extendio.es{DATA[product].get("poster") or DATA[product]["image"]}"><link rel="icon" href="/assets/favicon-32.png"><link rel="stylesheet" href="/assets/fonts.css"><link rel="stylesheet" href="/assets/product-guide.css"><script type="application/ld+json">{json.dumps(schema,ensure_ascii=False)}</script><script src="/assets/consent.js?v=20260903" defer></script></head><body>
<header class="top"><div class="wrap"><a href="/{lang}/"><img class="logo" src="/assets/logo.png" alt="Extendio"></a><a class="back" href="/{lang}/#produkte">← {c["back"]}</a><nav class="langs" aria-label="Language">{langlinks}</nav></div></header>
<main><div class="wrap"><div class="crumb"><a href="/{lang}/">{c["home"]}</a> / {escape(d["title"])}</div><section class="hero"><div class="media">{media}</div><div><p class="kicker">{c["kicker"]}</p><h1>{escape(d["title"])}</h1><p class="lead">{escape(d["lead"])}</p><div class="facts">{pills}</div><div class="actions"><a class="btn" data-buy="{product}" data-cta-position="product_guide_top" href="{amazon}" target="_blank" rel="noopener">{c["buy"]}</a><a class="btn secondary" href="#details">{c["details"]}</a></div><p class="note">{c["price"]}</p></div></section></div>
<section class="section white" id="details"><div class="wrap"><h2>{c["details"]}</h2><div class="grid">{features}</div></div></section>
{reviews}
<section class="section"><div class="wrap"><h2>{c["faq"]}</h2>{faqs}</div></section>
<section class="section trust"><div class="wrap"><h2>{c["trust"]}</h2><div class="grid"><article class="box"><h3>{fact_h}</h3><p>{fact_p}</p></article><article class="box"><h3>{c["trust2h"]}</h3><p>{c["trust2p"]}</p></article><article class="box"><h3>{c["trust3h"]}</h3><p>{c["trust3p"]}</p></article></div></div></section>
<section class="final"><h2>{c["finalh"]}</h2><p>{c["finalp"]}</p><a class="btn" data-buy="{product}" data-cta-position="product_guide_bottom" href="{amazon}" target="_blank" rel="noopener">{c["buy"]}</a></section></main>
<footer><div class="wrap foot"><div><img src="/assets/logo.png" alt="Extendio"><p>Extendio · Alicante</p></div><div><p><a href="/{lang}/">{c["home"]}</a><br><a href="/{lang}/#grosshandel">B2B / Wholesale</a></p></div><div class="legal"><a href="/legal.html">{c["legal"]}</a><a href="/privacy.html">{c["privacy"]}</a><a href="/cookies.html">{c["cookies"]}</a><a href="#" data-cookie-settings>{c["settings"]}</a></div></div></footer>
<script>document.addEventListener('click',function(e){{const a=e.target.closest('[data-buy]');if(a&&window.trackExtendioEvent)window.trackExtendioEvent('amazon_click',{{product_id:a.dataset.buy,marketplace:new URL(a.href).hostname,language:'{lang}',cta_position:a.dataset.ctaPosition,link_url:a.href}})}});if(matchMedia('(prefers-reduced-motion:reduce)').matches)document.querySelectorAll('video').forEach(v=>{{v.removeAttribute('autoplay');v.pause()}});</script></body></html>"""

for product in DATA:
  for lang in ("de","es","en"):
    out = ROOT / lang / ROUTES[product][lang] / "index.html"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(page(product, lang), encoding="utf-8")
print(f"Generated {len(DATA) * 3} product guide pages.")
